"use strict";
// Описати масив об’єктів – сайтів розроблених компанією з такими властивостями
if (confirm('Почати тестування?')) {
    let dataList = [
        {
            id: 344277463,
            old_price: 1395,
            old_usd_price: '37.70',
            price: 1099,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '29.70',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 363766641,
            old_price: 0,
            old_usd_price: '0.00',
            price: 90,
            min_month_price: 0,
            sell_status: 'unavailable',
            status: 'active',
            usd_price: '2.43',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 339273715,
            old_price: 38,
            old_usd_price: '1.03',
            price: 25,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '0.68',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 330746665,
            old_price: 3087,
            old_usd_price: '83.43',
            price: 2548,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '68.86',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 344972806,
            old_price: 699,
            old_usd_price: '18.89',
            price: 549,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '14.84',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 318302299,
            old_price: 0,
            old_usd_price: '0.00',
            price: 8500,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '229.73',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 361430565,
            old_price: 3500,
            old_usd_price: '94.59',
            price: 1999,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '54.03',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 14429030,
            old_price: 3339,
            old_usd_price: '90.24',
            price: 2999,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '81.05',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 56340912,
            old_price: 2094,
            old_usd_price: '56.59',
            price: 1776,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '48.00',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 315292225,
            old_price: 1799,
            old_usd_price: '48.62',
            price: 1499,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '40.51',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 28437961,
            old_price: 42999,
            old_usd_price: '1162.14',
            price: 33999,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '918.89',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 339896833,
            old_price: 6399,
            old_usd_price: '172.95',
            price: 5899,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '159.43',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 364354149,
            old_price: 1600,
            old_usd_price: '43.24',
            price: 1500,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '40.54',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: {
                id: 106,
                discount_price: 1300,
                title: 'ціна по промокоду діє з 22.03 по 28.03',
                price_show_in_site_id: 5151,
                show_in_details: 1,
                show_in_catalog: 1,
                is_description: 1,
                description: 'test',
                promo_code: '',
                url_for_image: 'https://rozetka.com.ua/ua/promo/allgalaxies/',
                images: '',
                images_mobile: '',
                hide_price: 0,
            },
        },
        {
            id: 363184995,
            old_price: 0,
            old_usd_price: '0.00',
            price: 4499,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '121.59',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 98077846,
            old_price: 0,
            old_usd_price: '0.00',
            price: 3113,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '84.14',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 310694668,
            old_price: 0,
            old_usd_price: '0.00',
            price: 3000,
            min_month_price: 0,
            sell_status: 'unavailable',
            status: 'active',
            usd_price: '81.08',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 362812029,
            old_price: 0,
            old_usd_price: '0.00',
            price: 21700,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '586.49',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 361422708,
            old_price: 4100,
            old_usd_price: '110.81',
            price: 2699,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '72.95',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 318302257,
            old_price: 0,
            old_usd_price: '0.00',
            price: 8500,
            min_month_price: 0,
            sell_status: 'unavailable',
            status: 'active',
            usd_price: '229.73',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 310694498,
            old_price: 0,
            old_usd_price: '0.00',
            price: 2963,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '80.08',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 363651273,
            old_price: 5199,
            old_usd_price: '140.51',
            price: 4890,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '132.16',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 330747022,
            old_price: 3087,
            old_usd_price: '83.43',
            price: 2606,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '70.43',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 362617635,
            old_price: 4872,
            old_usd_price: '131.68',
            price: 2436,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '65.84',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 363614439,
            old_price: 5199,
            old_usd_price: '140.51',
            price: 4890,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '132.16',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
    ];
    document.write(`
    <h2>Розв'язки:</h2>
    <ol>
    `);
    //* === Задача 1. Знайти загальну вартість (нові ціни - price)
    const totalPrice = dataList.reduce((prevSum, product) => prevSum + product.price, 0);
    document.write(`
    <li>Загальна вартість: <strong>${totalPrice}грн</strong></li>
    `);
    //* === Задача 2. Знайти кількість товарів, у яких ціна зменшилась (price < old_price).
    const countOfProductsWithLessPrice = dataList.reduce((prevCount, product) => product.price < product.old_price ? prevCount + 1 : prevCount, 0);
    document.write(`
      <li>Кількість товарів, у яких ціна зменшилась: <strong>${countOfProductsWithLessPrice}</strong></li>
    `);
    //* === Задача 3. Знайти товари, які доступні (sell_status:"available")
    const availableProducts = dataList.filter((product) => product.sell_status === 'available');
    document.write(`
      <li>Виводжу тільки id товарів, які доступні у вигляді масива<br/>
          [
      `);
    availableProducts.forEach((product) => {
        document.write(`${product.id}, `);
    });
    document.write(`
        ]
        </li>
      `);
    //* === Задача 4.Cформувати новий список об”єктів тільки доступних  для продажу товарів, 
    //* які міститимуть тільки ідентифікатор товару (id), нову ціну (price), стару ціну (old_price), 
    //* та ціну у доларах (usd_price)
    function getCopyArrayWithShortProductData(dataList) {
        const newProductList = dataList.filter(product => product.sell_status === 'available').map((product) => {
            let { id, price, old_price, usd_price } = product;
            return {
                id,
                price,
                old_price,
                usd_price
            };
        });
        return newProductList;
    }
    const copyNewProductList = getCopyArrayWithShortProductData(dataList);
    document.write(`
      <li>сформувати новий список об”єктів тільки доступних  для продажу товарів, які міститимуть тільки ідентифікатор товару (id), нову ціну (price), стару ціну (old_price), та ціну у доларах (usd_price)
      `);
    document.write('<h2 style="font-family: Arial; color: #2c3e50;">Available Products for Sale</h2>');
    document.write('<table border="1" cellspacing="0" cellpadding="8" style="border-collapse: collapse; font-family: Arial; font-size: 15px;">');
    document.write('<tr style="background-color: #f0f0f0;">');
    document.write('<th>ID</th>');
    document.write('<th>New Price (₴)</th>');
    document.write('<th>Old Price (₴)</th>');
    document.write('<th>USD Price ($)</th>');
    document.write('</tr>');
    copyNewProductList.forEach((product, index) => {
        document.write(`
        <tr style="background-color: ${index % 2 === 0 ? '#ffffff' : '#f9f9f9'};">
          <td style="text-align: center;">${product.id}</td>
          <td style="text-align: right;">${product.price}</td>
          <td style="text-align: right; color: gray; text-decoration: line-through;">${product.old_price !== 0 ? product.old_price : '-'}</td>
          <td style="text-align: right; color: green;">${product.usd_price ? product.usd_price : '-'}</td>
        </tr>
      `);
    });
    document.write(`
        
        </li>
      `);
    document.write('</table>');
    document.write(`</ol>`);
}
